image: "python:3.9.15"

before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - lint
  - test

Lint:
  stage: lint
  script:
    - pylama -l mccabe,pep257,pep8,pycodestyle,pyflakes -v .
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'

Test:
  stage: test
  script:
    - pytest -v test --cov-report xml --cov=view --cov=model --cov=configuration --cov=website --cov=command --cov=route
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

